### ISSUE TITLE
blast command is not installed via brew

### ISSUE THREAD

**Issue by sannysoft** [dave/blast#2]
After installing blast via brew - command not found: blast

**Comment by dave** [comment]
Hmm I'm not a brew expert... do other brew installed commands work on your system? Perhaps the brew installation directory isn't in your path?

**Comment by sannysoft** [comment]
There is no file called blast even.
In /usr/local/Cellar/blast/2.7.1/bin there are blastn, blastx, blastp but no blast

**Comment by dave** [comment]
As I say I'm not really a brew expert... You might want to open a ticket in the brew repo, or get some help from brew experts?

Alternatively if you have Go installed, you can install with `go get -u github.com/dave/blast`

... or download one of the executables manually on the release page: https://github.com/dave/blast/releases

**Comment by dave** [comment]
You could also ask over in https://github.com/goreleaser/goreleaser - that's the tool I use to do the releases of blast. They probably know a lot more about how the brew integration works...

**Comment by dave** [comment]
Hey I'm going to close this but feel free to re-open if it's still a problem...
